library(catmaid)
library(nat.nblast)

y5 = read.neurons.catmaid("annotation:NAMK_putative_PAM-y5")
# convert to microns and resample to 1µm segments
y5.dps = dotprops(y5/1e3, resample=1, k=5)
y5.aba = nblast_allbyall(y5.dps, UseAlpha = T)
y5.hclust = nhclust(scoremat = y5.aba)
plot(y5.hclust)
plot(y5.hclust, labels = y5[,'name'] )
clear3d()
plot3d(y5.hclust, db=y5, k=3)


y5_L = read.neurons.catmaid("annotation:NAMK_putative_PAM-y5_LEFT")
my5_L = mirror_brain(y5_L, brain = FAFB14, transform = "flip")
y5_R = read.neurons.catmaid("annotation:NAMK_putative_PAM-y5_RIGHT")
y5_all <- c(my5_L, y5_R)
clear3d()
plot3d(y5_all, soma = TRUE)
plot3d(y5_R)
plot3d(FAFB14)

y5.dps = dotprops(y5_all/1e3, resample=1, k=5)
y5.aba = nblast_allbyall(y5.dps, UseAlpha = T)
y5.hclust = nhclust(scoremat = y5.aba)
plot(y5.hclust)
plot(y5.hclust, labels = y5_all[,'name'] )
clear3d()
plot3d(y5.hclust, db=y5, k=3, soma = TRUE)


library(nat)
library(elmr)

y5L = read.neurons.catmaid("annotation:NAMK_putative_PAM-y5_LEFT")
y5R = read.neurons.catmaid("annotation:NAMK_putative_PAM-y5_RIGHT")
y5L.FCWB=xform_brain(y5L, sample=FAFB14, reference=FCWB)
y5L.FCWBm = mirror_brain(y5L.FCWB)
y5R.FCWB=xform_brain(y5R, sample=FAFB14, reference=FCWB)
y5.FCWB.onesided= c(y5R.FCWB, y5L.FCWBm)
nopen3d()
plot3d(y5.FCWB.onesided, soma=TRUE)
plot3d(FCWB)
clear3d()
plot3d(y5L.FCWBm, col = "red", soma = TRUE)
